import { HISTORY } from './bossHistory';

export const getHistoryById = (id: number) => {
  const historyItem = HISTORY.find((item) => item.id === id);
  return historyItem ? historyItem.history : 'History not found';
};
export const getDesciptionById = (id: number) => {
  const descriptionItem = HISTORY.find((item) => item.id === id);

  return descriptionItem
    ? descriptionItem.description
    : 'Description not found';
};
export const BOSS = [
  {
    id: 1,
    title: 'Assaultron 9000',
    description: getDesciptionById(1),
    imageUrl: require('../assets/image/boss/15/15_Assaultron_9000.png'),
    level: 17,
    respawnMap: 'Proelium Frontier (lV1~15)',
    respawnTime: '17:00 ~ 17:20 Hs(s)',
    pvpZone: 15,
    history: getHistoryById(1),
    mapUrl: require('../assets/image/map/15/Proelium_Frontier.png'),
  },
  {
    id: 2,
    title: 'Mobile Siege Mech',
    description: getDesciptionById(2),
    imageUrl: require('../assets/image/boss/15/15_Mobile_SIege_Mech.png'),
    level: 17,
    respawnMap: 'Proelium Frontier (lV1~15)',
    respawnTime: '17:00 ~ 17:20 Hs(s)',
    pvpZone: 15,
    history: getHistoryById(2),
    mapUrl: require('../assets/image/map/15/Proelium_Frontier.png'),
  },
  {
    id: 3,
    title: 'Strategist AI',
    description: getDesciptionById(3),
    imageUrl: require('../assets/image/boss/15/15_Strategist_AI.png'),
    mapUrl: require('../assets/image/map/15/Proelium_Frontier.png'),
    level: 17,
    respawnMap: 'Proelium Frontier (lV1~15)',
    respawnTime: '17:00 ~ 17:20 Hs(s)',
    pvpZone: 15,
    history: getHistoryById(3),
  },
  {
    id: 4,
    title: 'Guardian AI',
    description: getDesciptionById(4),
    imageUrl: require('../assets/image/boss/15/15_Guardian_AI.png'),
    level: 17,
    respawnMap: 'Proelium Frontier (lV1~15)',
    respawnTime: '17:00 ~ 17:20 Hs(s)',
    pvpZone: 15,
    history: getHistoryById(4),
    mapUrl: require('../assets/image/map/15/Proelium_Frontier.png'),
  },
  {
    id: 5,
    title: 'Not a Bot',
    description: getDesciptionById(5),
    imageUrl: require('../assets/image/boss/15/15_Not_A_Bot.png'),
    mapUrl: require('../assets/image/map/15/Proelium_Frontier.png'),
    level: 17,
    respawnMap: 'Proelium Frontier (lV1~15)',
    respawnTime: '17:00 ~ 17:20 Hs(s)',
    pvpZone: 15,
    history: getHistoryById(5),
  },
  {
    id: 6,
    title: 'Kalayavan The Undying',
    description: getDesciptionById(6),
    imageUrl: require('../assets/image/boss/30/30_Kalayavan_The_Undying.png'),
    level: 17,
    respawnMap: 'Cantabilian (lV20~30)',
    respawnTime: '9:00 ~ 9:20 Hs(s)',
    pvpZone: 30,
    history: getHistoryById(6),
    mapUrl: require('../assets/image/map/15/Proelium_Frontier.png'),
  },
  {
    id: 7,
    title: 'Raptor Slayer',
    description: getDesciptionById(7),
    imageUrl: require('../assets/image/boss/80/80_raigo_Raptor_Slayer.png'),
    level: 82,
    respawnMap: 'D-Water Borderland (lV31~80)',
    respawnTime: '12:00 ~ 12:20 Hs(s)',
    pvpZone: 80,
    history: getHistoryById(7),
    mapUrl: require('../assets/image/map/15/Proelium_Frontier.png'),
  },
  {
    id: 8,
    title: 'Luminous Brigand',
    description: getDesciptionById(8),
    imageUrl: require('../assets/image/boss/80/80_raigo_Luminous_Brigand.png'),
    level: 82,
    respawnMap: 'D-Water Borderland (lV31~80)',
    respawnTime: '12:00 ~ 12:20 Hs(s)',
    pvpZone: 80,
    history: getHistoryById(8),
    mapUrl: require('../assets/image/map/15/Proelium_Frontier.png'),
  },
  {
    id: 9,
    title: 'Greendieta Seraphim',
    description: getDesciptionById(9),
    imageUrl: require('../assets/image/boss/80/80_raigoCaver_Greendieta_Seraphim.png'),
    level: 84,
    respawnMap: 'Caelum Greendieta (lV31~80)',
    respawnTime: '10:00 ~ 10:20 Hs(s)',
    pvpZone: 80,
    history: getHistoryById(9),
    mapUrl: require('../assets/image/map/15/Proelium_Frontier.png'),
  },
  {
    id: 10,
    title: 'Dios Exiel',
    description: getDesciptionById(10),
    imageUrl: require('../assets/image/boss/80/80_raigoCaver_Dios_Exiel.png'),
    level: 84,
    respawnMap: 'Caelum Sacra (lV31~80)',
    respawnTime: '15:00 ~ 15:20 Hs(s)',
    pvpZone: 80,
    history: getHistoryById(10),
    mapUrl: require('../assets/image/map/15/Proelium_Frontier.png'),
  },
  {
    id: 11,
    title: 'Gaia ',
    description: getDesciptionById(11),
    imageUrl: require('../assets/image/boss/80/80_event_Gaia.png'),
    level: 84,
    respawnMap: 'Event ??',
    respawnTime: 'Event ??',
    pvpZone: 'Event',
    history: getHistoryById(11),
    mapUrl: require('../assets/image/map/15/Proelium_Frontier.png'),
  },
  {
    id: 12,
    title: 'Princess Rirumu',
    description: getDesciptionById(12),
    imageUrl: require('../assets/image/boss/80/80_Princess_Rirumu.png'),
    level: 83,
    respawnMap: 'Volcano Island (lV80)',
    respawnTime: '9:00 ~ 12:00 Hs(s)',
    pvpZone: 80,
    history: getHistoryById(12),
    mapUrl: require('../assets/image/map/15/Proelium_Frontier.png'),
  },
  {
    id: 13,
    title: 'Cryptic the Last',
    description: getDesciptionById(7),
    imageUrl: require('../assets/image/boss/80/80_kanosCaver_Cryptic_the_Last.png'),
    level: 75,
    respawnMap: '??',
    respawnTime: '??',
    pvpZone: 80,
    history: getHistoryById(13),
    mapUrl: require('../assets/image/map/15/Proelium_Frontier.png'),
  },
  {
    id: 14,
    title: 'Cryptic Bulldozer',
    description: getDesciptionById(7),
    imageUrl: require('../assets/image/boss/80/80_kanosCaver_Cryptic_Bulldozer.png'),
    level: 75,
    respawnMap: '??',
    respawnTime: '??',
    pvpZone: 80,
    history: getHistoryById(14),
    mapUrl: require('../assets/image/map/15/Proelium_Frontier.png'),
  },
  {
    id: 15,
    title: 'Cannibal Hydra',
    description: getDesciptionById(7),
    imageUrl: require('../assets/image/boss/80/80_kanosCaver_Cannibal_Hydra.png'),
    level: 75,
    respawnMap: '??',
    respawnTime: '??',
    pvpZone: 80,
    history: getHistoryById(15),
    mapUrl: require('../assets/image/map/15/Proelium_Frontier.png'),
  },
  {
    id: 16,
    title: 'Cryptic Back',
    description: getDesciptionById(7),
    imageUrl: require('../assets/image/boss/80/80_kanosCaver_Cryptic_Back.png'),
    level: 75,
    respawnMap: '??',
    respawnTime: '??',
    pvpZone: 80,
    history: getHistoryById(16),
    mapUrl: require('../assets/image/map/15/Proelium_Frontier.png'),
  },
  {
    id: 17,
    title: 'Cryptic the Immortal',
    description: getDesciptionById(7),
    imageUrl: require('../assets/image/boss/80/80_kanosCaver_Cryptic_the_Immortal.png'),
    level: 75,
    respawnMap: '??',
    respawnTime: '??',
    pvpZone: 80,
    history: getHistoryById(17),
    mapUrl: require('../assets/image/map/15/Proelium_Frontier.png'),
  },
  {
    id: 18,
    title: 'Fury Kirihiross',
    description: getDesciptionById(7),
    imageUrl: require('../assets/image/boss/80/80_kanosCaver_Fury_Kirihiross.png'),
    level: 75,
    respawnMap: '??',
    respawnTime: '??',
    pvpZone: 80,
    history: getHistoryById(18),
    mapUrl: require('../assets/image/map/15/Proelium_Frontier.png'),
  },
  {
    id: 19,
    title: 'Dlizabeth Eathory',
    description: getDesciptionById(7),
    imageUrl: require('../assets/image/boss/80/80_kanosCaver_Dlizabeth_Eathory.png'),
    level: 75,
    respawnMap: '??',
    respawnTime: '??',
    pvpZone: 80,
    history: getHistoryById(19),
    mapUrl: require('../assets/image/map/15/Proelium_Frontier.png'),
  },
  {
    id: 20,
    title: 'Fierce Nantarios',
    description: getDesciptionById(7),
    imageUrl: require('../assets/image/boss/80/80_kanosCaver_Fierce_Nantarios.png'),
    level: 75,
    respawnMap: '??',
    respawnTime: '??',
    pvpZone: 80,
    history: getHistoryById(20),
    mapUrl: require('../assets/image/map/15/Proelium_Frontier.png'),
  },
  {
    id: 21,
    title: 'Lumen',
    description: getDesciptionById(7),
    imageUrl: require('../assets/image/boss/80/80_kanos_Lumen.png'),
    level: 82,
    respawnMap: 'Kanos Illium (lV70-80)',
    respawnTime: '17:00 ~ 17:20 Hs(s)',
    pvpZone: 80,
    history: getHistoryById(21),
    mapUrl: require('../assets/image/map/15/Proelium_Frontier.png'),
  },
  {
    id: 22,
    title: 'Ales',
    description: getDesciptionById(7),
    imageUrl: require('../assets/image/boss/80/80_kanos_Ales.png'),
    level: 82,
    respawnMap: 'Kanos Illium (lV70-80)',
    respawnTime: '17:00 ~ 17:20 Hs(s)',
    pvpZone: 80,
    history: getHistoryById(22),
    mapUrl: require('../assets/image/map/15/Proelium_Frontier.png'),
  },
  {
    id: 23,
    title: 'Dentatus',
    description: getDesciptionById(7),
    imageUrl: require('../assets/image/boss/80/80_kanos_Dentatus.png'),
    level: 82,
    respawnMap: 'Kanos Illium (lV70-80)',
    respawnTime: '17:00 ~ 17:20 Hs(s)',
    pvpZone: 80,
    history: getHistoryById(23),
    mapUrl: require('../assets/image/map/15/Proelium_Frontier.png'),
  },
  {
    id: 24,
    title: 'Secreta',
    description: getDesciptionById(7),
    imageUrl: require('../assets/image/boss/80/80_kanos_Secreta.png'),
    level: 82,
    respawnMap: 'Kanos Illium (lV70-80)',
    respawnTime: '17:00 ~ 17:20 Hs(s)',
    pvpZone: 80,
    history: getHistoryById(24),
    mapUrl: require('../assets/image/map/15/Proelium_Frontier.png'),
  },
  {
    id: 25,
    title: 'Commander Opal Hammer',
    description: getDesciptionById(7),
    imageUrl: require('../assets/image/boss/80/80_jungle_Commander_Opal_Hammer.png'),
    level: 84,
    respawnMap: 'Stable Erde (lV55-80)',
    respawnTime: '10:00 ~ 10:20 Hs(s)',
    pvpZone: 80,
    history: getHistoryById(25),
    mapUrl: require('../assets/image/map/15/Proelium_Frontier.png'),
  },
  {
    id: 26,
    title: 'Graveyard Teroro',
    description: getDesciptionById(7),
    imageUrl: require('../assets/image/boss/80/80_locus_Graveyard_Terror.png'),
    level: 85,
    respawnMap: 'Locus Graveyard (lV80)',
    respawnTime: '9:00 ~ 9:20 Hs(s)',
    pvpZone: 80,
    history: getHistoryById(26),
    mapUrl: require('../assets/image/map/15/Proelium_Frontier.png'),
  },
  {
    id: 27,
    title: 'Dark Lord',
    description: getDesciptionById(7),
    imageUrl: require('../assets/image/boss/80/80_locus_Dark_Lord.png'),
    level: 85,
    respawnMap: 'Locus Graveyard (lV80)',
    respawnTime: '8:00 ~ 8:20 Hs(s)',
    pvpZone: 80,
    history: getHistoryById(27),
    mapUrl: require('../assets/image/map/15/Proelium_Frontier.png'),
  },
  {
    id: 28,
    title: 'Abyssal Eclipser Umbraxis',
    description: getDesciptionById(7),
    imageUrl: require('../assets/image/boss/80/80_dragon_Abyssal_Eclipser_Umbraxis.png'),
    level: 83,
    respawnMap: 'Dragonspine Enclave (lV80)',
    respawnTime: '??',
    pvpZone: 80,
    history: getHistoryById(28),
    mapUrl: require('../assets/image/map/15/Proelium_Frontier.png'),
  },
  {
    id: 29,
    title: 'Tempest Guardian Terravane',
    description: getDesciptionById(7),
    imageUrl: require('../assets/image/boss/80/80_dragon_Tempest_Guardian_Terravane.png'),
    level: 82,
    respawnMap: 'Dragonspine Enclave (lV80)',
    respawnTime: '??',
    pvpZone: 80,
    history: getHistoryById(29),
    mapUrl: require('../assets/image/map/15/Proelium_Frontier.png'),
  },
  {
    id: 30,
    title: 'Pestilent Tyrant Nidhogg',
    description: getDesciptionById(7),
    imageUrl: require('../assets/image/boss/80/80_dragon_Pestilent_Tyrant_Nidhogg.png'),
    level: 82,
    respawnMap: 'Dragonspine Enclave (lV80)',
    respawnTime: '??',
    pvpZone: 80,
    history: getHistoryById(30),
    mapUrl: require('../assets/image/map/15/Proelium_Frontier.png'),
  },
  {
    id: 31,
    title: 'Firestorm Warden Pyralis',
    description: getDesciptionById(7),
    imageUrl: require('../assets/image/boss/80/80_dragon_Firestorm_Warden_Pyralis.png'),
    level: 82,
    respawnMap: 'Dragonspine Enclave (lV80)',
    respawnTime: '??',
    pvpZone: 80,
    history: getHistoryById(31),
    mapUrl: require('../assets/image/map/15/Proelium_Frontier.png'),
  },
  {
    id: 32,
    title: 'Eternitys Vanquisher Stygion',
    description: getDesciptionById(7),
    imageUrl: require('../assets/image/boss/80/80_dragon_Eternitys_Vanquisher_Stygion.png'),
    level: 84,
    respawnMap: 'Dragonspine Enclave (lV80)',
    respawnTime: '??',
    pvpZone: 80,
    history: getHistoryById(32),
    mapUrl: require('../assets/image/map/15/Proelium_Frontier.png'),
  },

  {
    id: 33,
    title: 'Cloron Dragon',
    description:
      'The Phantom Dragon is an ethereal creature, composed of ghostly bones that float and move with supernatural energy. It haunts the cave that bears its name “Phantom’s Lair”, unable to be touched by conventional weapons. Its attacks are of spectral origin, causing both physical and spiritual damage.',
    imageUrl: require('../assets/image/boss/80/80_map1Caver_Cloron_Dragon.png'),
    level: 64,
    respawnMap: 'Cloron´s Lair (~map1)',
    respawnTime: '??',
    pvpZone: '??',
    history: getHistoryById(33),
    mapUrl: require('../assets/image/map/15/Proelium_Frontier.png'),
  },
  {
    id: 34,
    title: 'Fantasma Dragon',
    description:
      'The Cloron Dragon is an ancient dragon king who dwells within the ruins of Cloron’s Lair. He is colossal and imposing, with a presence that intimidates even the bravest warriors. His tough, ancient scales have withstood countless battles, and his power is legendary, devastating any enemy who attempts to invade his domain.',
    imageUrl: require('../assets/image/boss/80/80_map1Caver_Fantasma_Dragon.png'),
    level: 64,
    respawnMap: 'Fantasma´s Lair (~map1)',
    respawnTime: '??',
    pvpZone: '??',
    history: getHistoryById(34),
    mapUrl: require('../assets/image/map/15/Proelium_Frontier.png'),
  },
];
