export const WINGS = [
  { id: 0, name: 'Wings of Angels' },
  { id: 1, name: 'Wings of Illusion' },
  { id: 2, name: 'Wings of Deception' },
  { id: 3, name: 'Wings of Demons' },
  { id: 4, name: 'Wings of Thor' },
  { id: 5, name: 'Wings of Loki' },
  { id: 6, name: 'The Nightmare before Halloween' },
  { id: 7, name: 'Wings of the Phoenix' },
  { id: 8, name: 'Fiery Wings' },
  { id: 9, name: 'Fiery Tears' },
  { id: 10, name: 'Christmas Wings' },
  { id: 11, name: "Dominion's Wings" },
  { id: 12, name: 'Wings of Terror' },
  { id: 13, name: 'Unnamed' },
  { id: 14, name: 'Heavenly Wings' },
  { id: 15, name: 'Unnamed' },
  { id: 16, name: 'Unnamed' },
  { id: 17, name: 'Unnamed' },
  { id: 18, name: 'Fiery Dark Wings' },
  { id: 19, name: 'Fiery Dark Tears' },
  { id: 20, name: 'Sky Tears' },
  { id: 21, name: 'Sky Wings' },
  { id: 22, name: 'Christmas Wings (Golden)' },
  { id: 23, name: 'Christmas Wings (Silver)' },
  { id: 24, name: 'Morpho Menelaus' },
  { id: 25, name: "Lucifer's Wings" },
  { id: 26, name: "Throne's Wings" },
  { id: 27, name: 'Tinsel Ornament Wings' },
  { id: 28, name: 'Ruby Wings' },
  { id: 29, name: 'Emerarld Wings' },
  { id: 30, name: 'Unnamed' },
  { id: 31, name: 'Angel Wings' },
  { id: 32, name: 'HeliPack' },
  { id: 33, name: 'K-21 Wings' },
  { id: 34, name: 'Wings of the Killer' },
  { id: 35, name: 'Small Copper' },
  { id: 36, name: 'Small Ametrine' },
  { id: 37, name: 'Regal Fritillary' },
  { id: 38, name: 'August Fritillary' },
  { id: 39, name: 'Painted Lady' },
  { id: 40, name: 'Purple Lady' },
  { id: 41, name: 'Red Admiral' },
  { id: 42, name: 'Purple Admiral' },
  { id: 43, name: 'Monarch' },
  { id: 44, name: 'Purple Monarch' },
  { id: 45, name: 'Nephilim Wings' },
  { id: 46, name: 'Necromancer Wings' },
  { id: 47, name: 'Sweet Christmas Wings' },
  { id: 48, name: 'Garland Wings' },
  { id: 49, name: 'Ocean Wings' },
  { id: 50, name: 'Blossom Wings' },
  { id: 51, name: 'Burning Elevation' },
  { id: 52, name: 'Overflowing Mana' },
  { id: 53, name: 'Serene Flight' },
  { id: 54, name: 'Cethosia Wings' },
  { id: 55, name: 'Ancestral Dragon Wings' },
  { id: 56, name: 'Ancestral Shaman Wings' },
  { id: 57, name: 'Ancestral Divine Wings' },
  { id: 58, name: 'Molten Blade Wings' },
  { id: 59, name: 'Unnamed' },
  { id: 60, name: 'Unnamed' },
  { id: 61, name: 'Unnamed' },
  { id: 62, name: 'Unnamed' },
  { id: 63, name: 'Unnamed' },
  { id: 64, name: 'Unnamed' },
  { id: 65, name: 'Unnamed' },
  { id: 66, name: 'Unnamed' },
  { id: 67, name: 'Unnamed' },
  { id: 68, name: 'Unnamed' },
  { id: 69, name: 'Unnamed' },
  { id: 70, name: 'Dimensional Demon Wings' },
  { id: 71, name: 'Unnamed' },
  { id: 72, name: 'Unnamed' },
  { id: 73, name: 'Unnamed' },
  { id: 74, name: 'Unnamed' },
  { id: 75, name: 'Unnamed' },
  { id: 76, name: 'Unnamed' },
  { id: 77, name: 'Unnamed' },
  { id: 78, name: 'Unnamed' },
  { id: 79, name: 'Unnamed' },
  { id: 80, name: 'Wings of the Ancients' },
  { id: 81, name: 'Unnamed' },
  { id: 82, name: 'Unnamed' },
  { id: 83, name: 'Unnamed' },
  { id: 84, name: 'Unnamed' },
  { id: 85, name: 'Unnamed' },
  { id: 86, name: 'Unnamed' },
  { id: 87, name: 'Unnamed' },
  { id: 88, name: 'Unnamed' },
  { id: 89, name: 'Unnamed' },
  { id: 90, name: 'Unnamed' },
  { id: 91, name: 'Dimensional Demon Wings' },
  { id: 92, name: 'Dimensional Demon Wings' },
  { id: 93, name: 'Dimensional Demon Wings' },
  { id: 94, name: 'Dimensional Demon Wings' },
  { id: 95, name: 'Unnamed' },
  { id: 96, name: 'Unnamed' },
  { id: 97, name: 'Unnamed' },
  { id: 98, name: 'Unnamed' },
  { id: 99, name: 'Unnamed' },
  { id: 100, name: 'Unnamed' },
  { id: 101, name: 'Unnamed' },
  { id: 102, name: 'Unnamed' },
  { id: 103, name: 'Frozen Breath Wings' },
  { id: 104, name: 'Frozen Breath Wings' },
  { id: 105, name: 'Frozen Breath Wings' },
  { id: 106, name: 'Frozen Breath Wings' },
  { id: 107, name: 'Unnamed' },
  { id: 108, name: 'Unnamed' },
  { id: 109, name: 'Unnamed' },
  { id: 110, name: 'Unnamed' },
  { id: 111, name: 'Unnamed' },
  { id: 112, name: 'Unnamed' },
  { id: 113, name: 'Unnamed' },
  { id: 114, name: 'Unnamed' },
  { id: 115, name: 'Unnamed' },
  { id: 116, name: 'Unnamed' },
  { id: 117, name: 'Unnamed' },
  { id: 118, name: 'Magical Pixie Wings' },
  { id: 119, name: 'Unnamed' },
  { id: 120, name: 'Mercy Wings T1' },
  { id: 121, name: 'Unnamed' },
  { id: 122, name: 'Mercy Wings T2' },
  { id: 123, name: 'Unnamed' },
  { id: 124, name: 'Mercy Wings T3' },
  { id: 125, name: 'Unnamed' },
  { id: 126, name: 'Unnamed' },
  { id: 127, name: 'Unnamed' },
  { id: 128, name: 'Unnamed' },
  { id: 129, name: 'Unnamed' },
  { id: 130, name: 'Unnamed' },
  { id: 131, name: 'Unnamed' },
  { id: 132, name: 'Unnamed' },
  { id: 133, name: 'Unnamed' },
  { id: 134, name: 'Unnamed' },
  { id: 135, name: 'Unnamed' },
  { id: 136, name: 'Unnamed' },
  { id: 137, name: 'Unnamed' },
  { id: 138, name: 'Unnamed' },
  { id: 139, name: 'Spring Festival Wings' },
  { id: 140, name: 'Spring Festival Wings' },
  { id: 141, name: 'Spring Festival Wings' },
  { id: 142, name: 'Spring Festival Wings' },
  { id: 143, name: 'Celestial Embrace Wings' },
  { id: 144, name: ' Wings of Narya' },
  { id: 145, name: 'Grand Soulgem Wings' },
  { id: 146, name: 'Soulgem Wings' },
  { id: 147, name: 'Heart Wings' },
  { id: 148, name: 'Wings of Mairon' },
  { id: 149, name: "Nidhogg's Fragment" },
  { id: 150, name: 'War Banners' },
  { id: 151, name: 'Dark Fate Wings' },
  { id: 152, name: 'Bloody Crow Wings' },
  { id: 153, name: 'Firefinch Wings' },
  { id: 154, name: 'Glowing Sunset Wings' },
  { id: 155, name: 'Devil Valentine' },
  { id: 156, name: 'Dragon Bone Wings' },
];
