export const SKILLS = [
  {
    id: 1,
    skillBasic: require('../../assets/image/class/human/fight/skills/Fighter_Basic.png'),
    skillSingle: require('../../assets/image/class/human/fight/skills/Fighter_Single.png'),
    skillBuff: require('../../assets/image/class/human/fight/skills/Fighter_Buff.png'),
    skillRanger: require('../../assets/image/class/human/fight/skills/Fighter_Range.png'),
  },
  {
    id: 2,
    skillBasic: require('../../assets/image/class/human/defender/skills/Defender_Basic.png'),
    skillSingle: require('../../assets/image/class/human/defender/skills/Defender_Single.png'),
    skillBuff: require('../../assets/image/class/human/defender/skills/Defender_Buff.png'),
    skillRanger: require('../../assets/image/class/human/defender/skills/Defender_Range.png'),
  },
  {
    id: 3,
    skillBasic: require('../../assets/image/class/human/priest/skills/Priest_Basic.png'),
    skillSingle: require('../../assets/image/class/human/priest/skills/Priest_Single.png'),
    skillBuff: require('../../assets/image/class/human/priest/skills/Priest_Buff.png'),
    skillRanger: require('../../assets/image/class/human/priest/skills/Priest_Range.png'),
  },
  {
    id: 4,
    skillBasic: require('../../assets/image/class/elf/ranger/skills/Ranger_Buff.png'),
    skillSingle: require('../../assets/image/class/elf/ranger/skills/Ranger_Single.png'),
    skillBuff: require('../../assets/image/class/elf/ranger/skills/Ranger_Buff.png'),
    skillRanger: require('../../assets/image/class/elf/ranger/skills/Ranger_Range.png'),
  },
  {
    id: 5,
    skillBasic: require('../../assets/image/class/elf/archer/skills/Archer_Basic.png'),
    skillSingle: require('../../assets/image/class/elf/archer/skills/Archer_Single.png'),
    skillBuff: require('../../assets/image/class/elf/archer/skills/Archer_Buff.png'),
    skillRanger: require('../../assets/image/class/elf/archer/skills/Archer_Buff.png'),
  },
  {
    id: 6,
    skillBasic: require('../../assets/image/class/elf/mage/skills/Mage_Basic.png'),
    skillSingle: require('../../assets/image/class/elf/mage/skills/Mage_Single.png'),
    skillBuff: require('../../assets/image/class/elf/mage/skills/Mage_Buff.png'),
    skillRanger: require('../../assets/image/class/elf/mage/skills/Mage_Range.png'),
  },
  {
    id: 7,
    skillBasic: require('../../assets/image/class/spirity/monkey/skills/Monkey_Basic.png'),
    skillSingle: require('../../assets/image/class/spirity/monkey/skills/Monkey_Single.png'),
    skillBuff: require('../../assets/image/class/spirity/monkey/skills/Monkey_Buff.png'),
    skillRanger: require('../../assets/image/class/spirity/monkey/skills/Monkey_Range.png'),
  },
  {
    id: 8,
    skillBasic: require('../../assets/image/class/nordein/warrior/skills/Warrior_Basic.png'),
    skillSingle: require('../../assets/image/class/nordein/warrior/skills/Warrior_Single.png'),
    skillBuff: require('../../assets/image/class/nordein/warrior/skills/Warrior_Buff.png'),
    skillRanger: require('../../assets/image/class/nordein/warrior/skills/Warrior_Range.png'),
  },
  {
    id: 9,
    skillBasic: require('../../assets/image/class/nordein/guardian/skills/Guardian_Basic.png'),
    skillSingle: require('../../assets/image/class/nordein/guardian/skills/Guardian_Single.png'),
    skillBuff: require('../../assets/image/class/nordein/guardian/skills/Guardian_Buff.png'),
    skillRanger: require('../../assets/image/class/nordein/guardian/skills/Guardian_Range.png'),
  },
  {
    id: 10,
    skillBasic: require('../../assets/image/class/nordein/oracle/skills/Oracle_Basic.png'),
    skillSingle: require('../../assets/image/class/nordein/oracle/skills/Oracle_Single.png'),
    skillBuff: require('../../assets/image/class/nordein/oracle/skills/Oracle_Buff.png'),
    skillRanger: require('../../assets/image/class/nordein/oracle/skills/Oracle_Range.png'),
  },
  {
    id: 11,
    skillBasic: require('../../assets/image/class/vail/assassin/skills/Assassin_Basic.png'),
    skillSingle: require('../../assets/image/class/vail/assassin/skills/Assassin_Single.png'),
    skillBuff: require('../../assets/image/class/vail/assassin/skills/Assassin_Buff.png'),
    skillRanger: require('../../assets/image/class/vail/assassin/skills/Assassin_Buff.png'),
  },
  {
    id: 12,
    skillBasic: require('../../assets/image/class/vail/hunter/skills/Hunter_Basic.png'),
    skillSingle: require('../../assets/image/class/vail/hunter/skills/Hunter_Single.png'),
    skillBuff: require('../../assets/image/class/vail/hunter/skills/Hunter_Buff.png'),
    skillRanger: require('../../assets/image/class/vail/hunter/skills/Hunter_Range.png'),
  },
  {
    id: 13,
    skillBasic: require('../../assets/image/class/vail/pagan/skills/Pagan_Basic.png'),
    skillSingle: require('../../assets/image/class/vail/pagan/skills/Pagan_Single.png'),
    skillBuff: require('../../assets/image/class/vail/pagan/skills/Pagan_Buff.png'),
    skillRanger: require('../../assets/image/class/vail/pagan/skills/Pagan_Range.png'),
  },
  {
    id: 14,
    skillBasic: require('../../assets/image/class/spirity/druid/skills/Druid_Basic.png'),
    skillSingle: require('../../assets/image/class/spirity/druid/skills/Duid_Single.png'),
    skillBuff: require('../../assets/image/class/spirity/druid/skills/Druid_Buff.png'),
    skillRanger: require('../../assets/image/class/spirity/druid/skills/Druid_Range.png'),
  },
];
