export const DESCRIPTION = [
  {
    id: 1,
    description:
      'Fighters are masters of physical combat, specializing in dealing massive amounts of direct damage to their enemies. They wield a wide variety of melee weapons, such as swords, axes, and spears, making them true juggernauts on the front lines of combat. This class is ideal for players who enjoy the adrenaline rush of being in the heat of battle, delivering powerful blows while controlling the battlefield with their imposing presence. As the best DPS (damage per second) class, Fighters are capable of dealing massive amounts of damage in a short period of time, utilizing their abilities to maximize the effectiveness of their attacks. However, this class is not the best option for farming, due to their limited area-of-effect abilities, which can make it difficult to quickly eliminate groups of enemies. To reach their full potential, the Fighter relies on specific attributes: it is essential to invest in DEX (Dexterity) to dodge enemy attacks, with an ideal range between 3000 and 3500 DEX, ensuring effective hits and dodges. The remaining points should be allocated to STR (Strength) to increase the damage dealt. Fighters rely heavily on their skills to inflict damage, especially with the activation of Black Hole, which provides a bonus of 4% additional damage. The most notable skills include: Deadly Shock - Demon Strike - Bastard Swing - Whirling Dervish These skills are considered finishing moves, capable of delivering devastating blows. In PvP, Fighters often use their three main skills in quick succession to maximize their damage: - Deadly Strike - Hell’s Claw - Wild Rage. With this combination of powerful attacks and strategic skills, Fighters stand out as an unstoppable force on the battlefield, ready to face any challenge that comes their way.',
  },
  {
    id: 2,
    description:
      'Defenders are the frontline of the Alliance of Light, specializing in absorbing large amounts of damage and protecting their allies. With high durability and defensive abilities, they are formidable opponents who are difficult to take down. Wearing heavy armor and sturdy shields, Defenders not only hold the line, but also attract the attention of their enemies, becoming the focus of combat. The Defender class is the ultimate tank, ideal for farming and PvP situations. This class’s versatility allows it to easily transition between a pure tank and a DPS role, depending on the needs of the group. In most builds, tanks have at least 3000 DEX, complemented by a high STR rating, providing a lethal combination of resistance and attack power. The most effective combos for this class revolve around the powerful Entice and Greater Provocation abilities. These magical abilities not only bring enemies closer, but also render them defenseless for a short period of time, allowing Defenders to be used for both defensive and offensive purposes. In addition to their combat capabilities, Defenders possess an essential support ability: Dayfly Guard. This ability prevents damage to allies within its range, providing an additional layer of protection in critical moments. Another powerful support ability that is often underestimated is Mind Blast. This ability alters the perception of enemies, causing them to attack each other instead of their allies, and can be especially effective even against targets that have the Transformation ability active.',
  },
  {
    id: 3,
    description:
      'Priests, also known as Healers, are the essential human support class in Shaiya, dedicated to healing and protecting their allies in battle. With an arsenal of abilities designed to restore health to party members, remove debuffs, and even revive fallen teammates, Priests are essential to the team’s survival in challenging combats. This class not only ensures the team’s longevity during intense PvP encounters, but also simplifies the farming experience, making it much more efficient when teaming up with others. Without the presence of adequate healers, large-scale battles can become extremely difficult, as their defensive role is crucial. Priests are characterized by their high defensive capabilities, with robust stats and abilities that make them a prime target for enemies during PvP. Dedicating themselves to this class requires deep commitment, as the survival of the group often depends on their actions. One of their most powerful and essential abilities is Dispel, which allows them to remove any debuffs from targeted allies, ensuring that they remain effective and resilient in adverse situations. Additionally, healing abilities such as Regrowth and Great Healing provide a significant boost, allowing allies to continue pushing forward in raids against enemies. Priests should be proactive and not wait for a debuff to occur before taking action. Using their various skills and perks, they keep allies alive for longer, ensuring that the party can thrive in battle and excel in quests. With their powerful buffs and supportive abilities, Priests are like the linchpin of any team, ensuring that everyone has a fighting chance and a chance to win.',
  },
  {
    id: 4,
    description:
      'Rangers are masters of single combat (1v1) and stealth, known for ambushing their targets and killing them quickly from the shadows. They have the ability to blend in with their surroundings, moving invisibly and striking without warning. With great agility and precision, they are ideal for players who like to strike quickly and disappear without being caught. Specializing in stealthy and precise attacks,Rangers focus on eliminating enemies quickly and efficiently. Armed primarily with daggers and claws, their dexterity (DEX) is essential for dodging attacks and ensuring that their strikes are devastating. DEX-focused builds are the most common, as they offer a high dodge rating, allowing Rangers to avoid damage while delivering quick and lethal attacks. These combatants shine on the battlefield by roaming unseen, ready to ambush unsuspecting enemies. Their arsenal includes stunning abilities that can easily incapacitate opponents, leaving them defenseless against their rapid attacks. Additionally, they have scouting abilities that allow them to identify the element used by enemies, giving their team a valuable strategic advantage. While not as effective in large-scale PvP as other DPS-focused classes, Rangers have a crucial impact in smaller battles, where the precision and timing of their ambushes and stuns can turn the tide of combat. Their “Unlucky” ability, for example, can be extremely annoying to opponents, as it reduces DEX and LUC, making it difficult for them to react or escape. Despite being a difficult class to master,Rangers are essential allies in smaller PvP encounters and can become vital team members with practice and patience.',
  },
  {
    id: 5,
    description:
      'Archers are one of the most powerful and versatile classes, especially effective in PvP and farming situations. These sharpshooters specialize in ranged combat, utilizing longbows and crossbows to deliver precise and devastating strikes before their enemies can get close. With impressive crowd control and increased critical damage, Archers are ideal for players who prefer to keep their distance from their enemies, strategically attacking from afar. With common builds reaching 3,500 points in DEX (Dexterity) and LUC (Luck), they can deal large amounts of damage while maintaining a reasonable level of survivability. This allows Archers to excel in both PvP and farming, effectively dealing with massed enemies. The class has several AoE skills with short cooldowns, making them ideal for clearing groups of enemies quickly. Some of the most commonly used skills include: Bomber Sho - Blood Rain - Fan Shot - Arrow Bombing. Additionally, Hunters/Archers have control skills like Piercing Shot and Apocalyptic Shot that can temporarily immobilize enemies, giving them a tactical advantage on the battlefield. For sustained damage, Deadly Poison and Sustained Shot poison enemies, steadily reducing their HP over time. Finally, skills like Tranquilizing Shot reduce enemies’ STR (Strength) and REC (Recovery) stats, making them easier to defeat in prolonged combat.',
  },
  {
    id: 6,
    description:
      "The Mage class is the purest representation of attack in Shaiya, deeply connected to the natural elements. Its users wield fire, earth, water, and wind magic, capable of devastating both single targets and large areas with massive bursts of damage. While their physical defense is low, they make up for this weakness with the highest attack power in the game, boasting an impressive 16,000 magic power. These masters of the elements wield crowd-control abilities such as slow and paralysis, ensuring that their opponents are vulnerable to consecutive attacks. Magic Arrow, in particular, is the bane of melee classes, capable of dealing devastating damage with each strike, rapidly draining their enemies’ HP. When synchronized in a group, Mages have the power to obliterate entire groups of opponents in battle areas with destructive abilities such as Meteor Strike and Kamain Breath. The infamous meteor shower is feared across the battlefield, capable of turning the tide in your faction's favor or even ensuring complete devastation of your enemies. Despite its weakness in survivability and resistance, knowledge of the skill kit allows Mages to farm effectively and dominate battles with its annihilating attacks.",
  },
  {
    id: 7,
    description:
      "The Monkeys of the Bear Spirit Clan are disciplined warriors, skilled in hand-to-hand combat. Masters of the martial arts, they fight with staves and gloves, representing brute strength and agility. With a powerful body and a focused mind, the Monkeys are formidable tanks, capable of withstanding massive amounts of damage and striking back with devastating blows. Their combat philosophy is based on the harmony between body and spirit, making them pillars of physical strength and determination in Shaiya's wars.",
  },

  {
    id: 8,
    description:
      'Warriors are masters of physical combat, specializing in dealing massive amounts of direct damage to their enemies. They wield a wide variety of melee weapons, such as swords, axes, and spears, making them true juggernauts on the front lines of combat. This class is ideal for players who enjoy the adrenaline rush of being in the heat of battle, delivering powerful blows while controlling the battlefield with their imposing presence. As the best DPS (damage per second) class, Warriors are capable of dealing massive amounts of damage in a short period of time, utilizing their abilities to maximize the effectiveness of their attacks. However, this class is not the best option for farming, due to their limited area-of-effect abilities, which can make it difficult to quickly eliminate groups of enemies. To reach their full potential, the Warrior relies on specific attributes: it is essential to invest in DEX (Dexterity) to dodge enemy attacks, with an ideal range between 3000 and 3500 DEX, ensuring effective hits and dodges. The remaining points should be allocated to STR (Strength) to increase the damage dealt. Warriors rely heavily on their skills to inflict damage, especially with the activation of Black Hole, which provides a bonus of 4% additional damage. The most notable skills include: Deadly Shock - Demon Strike - Bastard Swing - Whirling Dervish These skills are considered finishing moves, capable of delivering devastating blows. In PvP, Warriors often use their three main skills in quick succession to maximize their damage: - Deadly Strike - Hell’s Claw - Wild Rage. With this combination of powerful attacks and strategic skills, Warriors stand out as an unstoppable force on the battlefield, ready to face any challenge that comes their way.',
  },
  {
    id: 9,
    description:
      'Guardians are the frontline of the Alliance of Darkness, specializing in absorbing large amounts of damage and protecting their allies. With high durability and defensive abilities, they are formidable opponents who are difficult to take down. Wearing heavy armor and sturdy shields, Guardians not only hold the line, but also attract the attention of their enemies, becoming the focus of combat. The Guardian class is the ultimate tank, ideal for farming and PvP situations. This class’s versatility allows it to easily transition between a pure tank and a DPS role, depending on the needs of the group. In most builds, tanks have at least 3000 DEX, complemented by a high STR rating, providing a lethal combination of resistance and attack power. The most effective combos for this class revolve around the powerful Entice and Greater Provocation abilities. These magical abilities not only bring enemies closer, but also render them defenseless for a short period of time, allowing Guardians to be used for both defensive and offensive purposes. In addition to their combat capabilities, Guardians possess an essential support ability: Dayfly Guard. This ability prevents damage to allies within its range, providing an additional layer of protection in critical moments. Another powerful support ability that is often underestimated is Mind Blast. This ability alters the perception of enemies, causing them to attack each other instead of their allies, and can be especially effective even against targets that have the Transformation ability active.',
  },
  {
    id: 10,
    description:
      'Oracles, also known as Healers, are a core Nordein support class in Shaiya, dedicated to healing and protecting their allies in battle. With an arsenal of abilities designed to restore health to party members, remove debuffs, and even resurrect fallen teammates, Oracles are essential for surviving challenging combats. Not only does this class ensure team longevity during intense PvP encounters, but it also simplifies the farming experience, making it much more efficient when teaming up with others. Without the proper presence of healers, large-scale battles can become extremely difficult, as their defensive role is crucial. Oracles are characterized by their high defensive capabilities, with robust stats and abilities that make them a prime target for enemies during PvP. Dedicating themselves to this class requires deep commitment, as the survival of the party often depends on their actions. One of their most powerful and essential abilities is Dispel, which allows them to remove any debuffs from targeted allies, ensuring that they remain effective and resilient in adverse situations. Additionally, healing abilities such as Regrowth and Great Healing provide a significant boost, allowing allies to continue pushing forward in raids against enemies. Oracles should be proactive and not wait for a debuff to occur before taking action. Using their various abilities and perks, they keep allies alive for longer, ensuring that the party can thrive in battle and excel in missions. With their powerful buffs and supportive abilities, Oracles are like the linchpin of any team, ensuring that everyone has a fighting chance and a winning one.',
  },
  {
    id: 11,
    description:
      'Assassins are masters of single combat (1v1) and stealth, known for ambushing their targets and killing them quickly from the shadows. They have the ability to blend in with their surroundings, moving invisibly and striking without warning. With great agility and precision, they are ideal for players who like to strike quickly and disappear without being caught. Specializing in stealthy and precise attacks, Assassins focus on eliminating enemies quickly and efficiently. Armed primarily with daggers and claws, their dexterity (DEX) is essential for dodging attacks and ensuring that their strikes are devastating. DEX-focused builds are the most common, as they offer a high dodge rating, allowing Assassins to avoid damage while delivering quick and lethal attacks. These combatants shine on the battlefield by roaming unseen, ready to ambush unsuspecting enemies. Their arsenal includes stunning abilities that can easily incapacitate opponents, leaving them defenseless against their rapid attacks. Additionally, they have scouting abilities that allow them to identify the element used by enemies, giving their team a valuable strategic advantage. While not as effective in large-scale PvP as other DPS-focused classes, Assassins have a crucial impact in smaller battles, where the precision and timing of their ambushes and stuns can turn the tide of combat. Their “Unlucky” ability, for example, can be extremely annoying to opponents, as it reduces DEX and LUC, making it difficult for them to react or escape. Despite being a difficult class to master, Assassins are essential allies in smaller PvP encounters and can become vital team members with practice and patience.',
  },
  {
    id: 12,
    description:
      'Hunters are one of the most powerful and versatile classes, especially effective in PvP and farming situations. These sharpshooters specialize in ranged combat, utilizing longbows and crossbows to deliver precise and devastating strikes before their enemies can get close. With impressive crowd control and increased critical damage, Hunters are ideal for players who prefer to keep their distance from their enemies, strategically attacking from afar. With common builds reaching 3,500 points in DEX (Dexterity) and LUC (Luck), they can deal large amounts of damage while maintaining a reasonable level of survivability. This allows Hunters to excel in both PvP and farming, effectively dealing with massed enemies. The class has several AoE skills with short cooldowns, making them ideal for clearing groups of enemies quickly. Some of the most commonly used skills include: Bomber Sho - Blood Rain - Fan Shot - Arrow Bombing. Additionally,Hunters  have control skills like Piercing Shot and Apocalyptic Shot that can temporarily immobilize enemies, giving them a tactical advantage on the battlefield. For sustained damage, Deadly Poison and Sustained Shot poison enemies, steadily reducing their HP over time. Finally, skills like Tranquilizing Shot reduce enemies’ STR (Strength) and REC (Recovery) stats, making them easier to defeat in prolonged combat.',
  },
  {
    id: 13,
    description:
      "The Pagan class is the purest representation of attack in Shaiya, deeply connected to the natural elements. Its users wield fire, earth, water, and wind magic, capable of devastating both single targets and large areas with massive bursts of damage. While their physical defense is low, they make up for this weakness with the highest attack power in the game, boasting an impressive 16,000 magic power. These masters of the elements wield crowd-control abilities such as slow and paralysis, ensuring that their opponents are vulnerable to consecutive attacks. Magic Arrow, in particular, is the bane of melee classes, capable of dealing devastating damage with each strike, rapidly draining their enemies’ HP. When synchronized in a group, Pagan have the power to obliterate entire groups of opponents in battle areas with destructive abilities such as Meteor Strike and Kamain Breath. The infamous meteor shower is feared across the battlefield, capable of turning the tide in your faction's favor or even ensuring complete devastation of your enemies. Despite its weakness in survivability and resistance, knowledge of the skill kit allows Pagans to farm effectively and dominate battles with its annihilating attacks.",
  },
  {
    id: 14,
    description:
      'Druids of the Bear Spirit Clan are spiritual guardians deeply connected to nature and the flow of life. They master the manipulation of the elements and possess powerful healing abilities, using the power of earth, wind, and plants to protect their allies. Patient and wise, Druids balance life and death, providing essential support in battle by revitalizing companions and weakening enemies with their natural magics. They are essential to maintaining harmony on the battlefield and in the lands of Shaiya.',
  },
];
