// id=,
// title1=,
// link1=,
// title2=,
// link2=,

export const LINKS = [
  //1-fighter
  {
    id: 1,
    Helmet: [
      'Craft Lapis Lv9',
      'Shrewd Lapis Lv9',
      'Dual Craft Lapis Lv6',
      'Dual Fortune Lapis Lv6',
      'Heart Lapis',
      'Star Lapis || Pure Lapis || Triple Craft',
    ],
    Armor: [
      'Craft Lapis Lv8',
      'Craft Lapis Lv7',
      'Shrewd Lapis Lv8',
      'Shrewd Lapis Lv7',
      'Dual Craft Lapis Lv6',
      'Elemental Lapis Lv2 || Elemental Orb',
    ],
    Gloves: [
      'Craft Lapis Lv9',
      'Shrewd Lapis Lv9',
      'Shrewd Lapis Lv8',
      'Shrewd Lapis Lv7',
      'Dual Craft Lapis Lv6',
      'Dual Fortune Lapis Lv6 || Triple Craft',
    ],
    Pants: [
      'Craft Lapis Lv9',
      'Craft Lapis Lv8',
      'Craft Lapis Lv7',
      'Shrewd Lapis Lv9',
      'Dual Craft Lapis Lv6',
      'Dual Fortune Lapis Lv6 || Triple Craft',
    ],
    Boots: [
      'Craft Lapis Lv8',
      'Craft Lapis Lv7',
      'Shrewd Lapis Lv8',
      'Shrewd Lapis Lv7',
      'Dual Craft Lapis Lv6',
      'Sonic Lapis Lv2',
    ],
  },
  //2 - defender
  {
    id: 2,
    Helmet: [
      'Craft Lapis Lv9',
      'Shrewd Lapis Lv9',
      'Dual Craft Lapis Lv6',
      'Dual Fortune Lapis Lv6',
      'Heart Lapis',
      'Star Lapis || Pure Lapis || Triple Craft Lapis',
    ],
    Armor: [
      'Craft Lapis Lv8',
      'Craft Lapis Lv7',
      'Shrewd Lapis Lv8',
      'Shrewd Lapis Lv7',
      'Dual Craft Lapis Lv6',
      'Elemental Lapis Lv2 || Elemental Orb',
    ],
    Gloves: [
      'Craft Lapis Lv9',
      'Shrewd Lapis Lv9',
      'Shrewd Lapis Lv8',
      'Shrewd Lapis Lv7',
      'Dual Craft Lapis Lv6',
      'Dual Fortune Lapis Lv6 || Triple Craft Lapis',
    ],
    Pants: [
      'Craft Lapis Lv9',
      'Craft Lapis Lv8',
      'Craft Lapis Lv7',
      'Shrewd Lapis Lv9',
      'Dual Craft Lapis Lv6',
      'Dual Fortune Lapis Lv6 || Triple Craft Lapis',
    ],
    Boots: [
      'Craft Lapis Lv8',
      'Craft Lapis Lv7',
      'Shrewd Lapis Lv8',
      'Shrewd Lapis Lv7',
      'Dual Craft Lapis Lv6',
      'Sonic Lapis Lv2',
    ],
    Shield: [
      'Craft Lapis Lv9',
      'Craft Lapis Lv8',
      'Craft Lapis Lv7',
      'Shrewd Lapis Lv9',
      'Dual Craft Lapis Lv6',
      'Dual Fortune Lapis Lv6 || Triple Craft Lapis',
    ],
  },
  //3 - defender
  {
    id: 22,
    Helmet: [
      'Life Lapis Lv8',
      'Life Lapis Lv7',
      'Safe Lapis Lv9',
      'Wit Lapis Lv7',
      'Wit Lapis Lv6',
      'Triple Craft Lapis',
    ],
    Armor: [
      'Absorption Lapis Lv9',
      'Absorption Lapis Lv8',
      'Absorption Lapis Lv7',
      'Life Lapis Lv9',
      'Life Lapis Lv8',
      'Life Lapis Lv7 || Elemental Lapis Lv2 || Elemental Orb',
    ],
    Gloves: [
      'Absorption Lapis Lv9',
      'Absorption Lapis Lv8',
      'Absorption Lapis Lv7',
      'Absorption Lapis Lv6 || Safe Lapis Lv9',
      'Life Lapis Lv8',
      'Life Lapis Lv7',
    ],
    Pants: [
      'Absorption Lapis Lv9',
      'Absorption Lapis Lv8',
      'Absorption Lapis Lv7',
      'Absorption Lapis Lv6 || Safe Lapis Lv9',
      'Life Lapis Lv8',
      'Life Lapis Lv7',
    ],
    Boots: [
      'Absorption Lapis Lv9',
      'Absorption Lapis Lv8',
      'Absorption Lapis Lv7',
      'Life Lapis Lv9',
      'Life Lapis Lv8',
      'Sonic Lapis Lv2',
    ],
    Shield: [
      'Absorption Lapis Lv9',
      'Absorption Lapis Lv8',
      'Absorption Lapis Lv7',
      'Absorption Lapis Lv6 || Safe Lapis Lv9',
      'Life Lapis Lv8',
      'Life Lapis Lv7',
    ],
  },
  //3 - priest
  {
    id: 3,
    Helmet: [
      'Life Lapis Lv8',
      'Life Lapis Lv7',
      'Safe Lapis Lv9',
      'Wise Lapis Lv9 || Dual Shrewd Lapis Lv6',
      'Dual Safe Lapis Lv6',
      'Triple Craft Lapis',
    ],
    Armor: [
      'Absorption Lapis Lv9',
      'Absorption Lapis Lv8',
      'Absorption Lapis Lv7',
      'Life Lapis Lv9',
      'Life Lapis Lv8',
      'Life Lapis Lv7 || Elemental Lapis Lv2 || Elemental Orb',
    ],
    Gloves: [
      'Absorption Lapis Lv9',
      'Absorption Lapis Lv8',
      'Absorption Lapis Lv7',
      'Absorption Lapis Lv6 || Safe Lapis Lv9',
      'Life Lapis Lv8',
      'Life Lapis Lv7',
    ],
    Pants: [
      'Absorption Lapis Lv9',
      'Absorption Lapis Lv8',
      'Absorption Lapis Lv7',
      'Absorption Lapis Lv6 || Safe Lapis Lv9',
      'Life Lapis Lv8',
      'Life Lapis Lv7',
    ],
    Boots: [
      'Absorption Lapis Lv9',
      'Absorption Lapis Lv8',
      'Absorption Lapis Lv7',
      'Life Lapis Lv9',
      'Life Lapis Lv8',
      'Sonic Lapis Lv2',
    ],
    //33 - priest/orcale
  },
  {
    id: 33,
    Helmet: [
      'Mystic Lapis Lv9',
      'Wise Lapis Lv9',
      'Fortune Lapis Lv9',
      'Dual Wise Lapis Lv6',
      'Dual Mystic Lapis Lv6',
      'Triple Mystic',
    ],
    Armor: [
      'Elemental Lapis Lv2 || Elemental Orb',
      'Mystic Lapis Lv8',
      'Mystic Lapis Lv7',
      'Fortune Lapis Lv8',
      'Dual Wise Lapis Lv6',
      'Triple Mystic Lapis',
    ],
    Gloves: [
      'Mystic Lapis Lv9',
      'Mystic Lapis Lv9',
      'Mystic Lapis Lv7 || Fortune Lapis Lv9',
      'Wise Lapis Lv9',
      'Wise Lapis Lv8',
      'Dual Wise Lapis Lv6',
    ],
    Pants: [
      'Mystic Lapis Lv9',
      'Mystic Lapis Lv8',
      'Mystic Lapis Lv7 || Fortune Lapis Lv9',
      'Wise Lapis Lv9',
      'Wise Lapis Lv8',
      'Dual Wise Lapis Lv6',
    ],
    Boots: [
      'Sonic Lapis Lv2',
      'Mystic Lapis Lv8',
      'Mystic Lapis Lv7',
      'Wise Lapis Lv8',
      'Wise Lapis Lv7 || Fortune Lapis Lv8',
      'Dual Mystic Lapis Lv6',
    ],
  },
  {
    id: 4,
    Helmet: [
      'Craft Lapis Lv9',
      'Shrewd Lapis Lv9',
      'Dual Craft Lapis Lv6',
      'Dual Fortune Lapis Lv6',
      'Heart Lapis',
      'Star Lapis || Pure Lapis',
    ],
    Armor: [
      'Craft Lapis Lv8',
      'Craft Lapis Lv7',
      'Shrewd Lapis Lv8',
      'Shrewd Lapis Lv7',
      'Dual Craft Lapis Lv6',
      'Elemental Lapis Lv2 || Elemental Orb',
    ],
    Gloves: [
      'Craft Lapis Lv9',
      'Shrewd Lapis Lv9',
      'Shrewd Lapis Lv8',
      'Shrewd Lapis Lv7',
      'Dual Craft Lapis Lv6',
      'Dual Fortune Lapis Lv6',
    ],
    Pants: [
      'Craft Lapis Lv9',
      'Craft Lapis Lv8',
      'Craft Lapis Lv7',
      'Shrewd Lapis Lv9',
      'Dual Craft Lapis Lv6',
      'Dual Fortune Lapis Lv6',
    ],
    Boots: [
      'Craft Lapis Lv8',
      'Craft Lapis Lv7',
      'Shrewd Lapis Lv8',
      'Shrewd Lapis Lv7',
      'Dual Craft Lapis Lv6',
      'Sonic Lapis Lv2',
    ],
  },
  {
    id: 44,
    Helmet: [
      'Life Lapis Lv7',
      'Life Lapis Lv8',
      'Shrewd Lapis Lv9',
      'Dual Craft Lapis Lv6',
      'Heart Lapis',
      'Triple Shrewd Lapis || Pure Lapis || Star Lapis',
    ],
    Armor: [
      'Elemental Lapis Lv2 || Elemental Orb',
      'Life Lapis Lv8',
      'Life Lapis Lv9',
      'Shrewd Lapis Lv8',
      'Shrewd Lapis Lv7',
      'Dual Craft Lapis Lv6 || Life Lapis Lv7',
    ],
    Gloves: [
      'Life Lapis Lv8',
      'Life Lapis Lv7',
      'Shrewd Lapis Lv9',
      'Shrewd Lapis Lv8',
      'Shrewd Lapis Lv7',
      'Dual Craft Lapis Lv6',
    ],
    Pants: [
      'Life Lapis Lv8',
      'Life Lapis Lv7',
      'Shrewd Lapis Lv9',
      'Dual Craft Lapis Lv6',
      'Craft Lapis Lv9 || Dual Fortune Lapis Lv6',
      'Dual Shrewd Lapis Lv6 || Triple Shrewd',
    ],
    Boots: [
      'Life Lapis Lv9',
      'Life Lapis Lv8',
      'Shrewd Lapis Lv8',
      'Shrewd Lapis Lv7',
      'Sonic Lapis Lv2',
      'Dual Craft Lapis Lv6 || Life Lapis Lv7',
    ],
  },
  {
    id: 5,
    Helmet: [
      'Shrewd Lapis Lv9',
      'Fortune Lapis Lv9',
      'Dual Fortune Lapis Lv6',
      'Triple Shrewd',
      'Heart Lapis',
      'Pure Lapis || Star Lapis',
    ],
    Armor: [
      'Elemental Lapis Lv2 || Elemental Orb',
      'Shrewd Lapis Lv8',
      'Shrewd Lapis Lv7',
      'Fortune Lapis Lv8',
      'Fortune Lapis Lv7',
      'Dual Fortune Lapis Lv6',
    ],
    Gloves: [
      'Shrewd Lapis Lv9',
      'Shrewd Lapis Lv8',
      'Shrewd Lapis Lv7',
      'Fortune Lapis Lv9',
      'Dual Fortune Lapis Lv6',
      'Triple Shrewd',
    ],
    pants: [
      'Shrewd Lapis Lv9',
      'Fortune Lapis Lv9',
      'Fortune Lapis Lv8',
      'Fortune Lapis Lv7',
      'Dual Fortune Lapis Lv6',
      'Triple Shrewd',
    ],
    Boots: [
      'Shrewd Lapis Lv8',
      'Shrewd Lapis Lv7',
      'Fortune Lapis Lv8',
      'Fortune Lapis Lv7',
      'Dual Fortune Lapis Lv6',
      'Sonic Lapis Lv2',
    ],
  },
  {
    id: 55,
    Helmet: [
      'Craft Lapis Lv9',
      'Fortune Lapis Lv9',
      'Dual Craft Lapis Lv6',
      'Dual Fortune Lapis Lv6',
      'Heart Lapis',
      'Pure Lapis || Star Lapis',
    ],
    Armor: [
      'Elemental Lapis Lv2 || Elemental Orb',
      'Craft Lapis Lv8',
      'Craft Lapis Lv7',
      'Fortune Lapis Lv8',
      'Fortune Lapis Lv7',
      'Dual Craft Lapis Lv6 || Dual Fortune Lapis Lv6',
    ],
    Gloves: [
      'Craft Lapis Lv9',
      'Fortune Lapis Lv9',
      'Shrewd Lapis Lv9',
      'Dual Craft Lapis Lv6',
      'Dual Fortune Lapis Lv6',
      'Triple Craft Lapis || Triple Shrewd Lapis',
    ],
    pants: [
      'Craft Lapis Lv9',
      'Craft Lapis Lv8',
      'Craft Lapis Lv7',
      'Fortune Lapis Lv9',
      'Fortune Lapis Lv8',
      'Fortune Lapis Lv7',
    ],
    Boots: [
      'Craft Lapis Lv8',
      'Craft Lapis Lv7',
      'Fortune Lapis Lv8',
      'Fortune Lapis Lv7',
      'Dual Craft Lapis Lv6 || Dual Fortune Lapis Lv6',
      'Sonic Lapis Lv2',
    ],
  },
  {
    id: 6,
    Helmet: [
      'Mystic Lapis Lv9',
      'Wise Lapis Lv9',
      'Fortune Lapis Lv9',
      'Dual Wise Lapis Lv6',
      'Dual Mystic Lapis Lv6',
      'Triple Mystic',
    ],
    Armor: [
      'Elemental Lapis Lv2 || Elemental Orb',
      'Mystic Lapis Lv8',
      'Mystic Lapis Lv7',
      'Fortune Lapis Lv8',
      'Dual Wise Lapis Lv6',
      'Triple Mystic Lapis',
    ],
    Gloves: [
      'Mystic Lapis Lv9',
      'Mystic Lapis Lv8',
      'Mystic Lapis Lv7 || Fortune Lapis Lv9',
      'Wise Lapis Lv9',
      'Wise Lapis Lv8',
      'Dual Wise Lapis Lv6',
    ],
    Pants: [
      'Mystic Lapis Lv9',
      'Mystic Lapis Lv8',
      'Mystic Lapis Lv7 || Fortune Lapis Lv9',
      'Wise Lapis Lv9',
      'Wise Lapis Lv8',
      'Dual Wise Lapis Lv6',
    ],
    Boots: [
      'Sonic Lapis Lv2',
      'Mystic Lapis Lv8',
      'Mystic Lapis Lv7',
      'Wise Lapis Lv8',
      'Wise Lapis Lv7 || Fortune Lapis Lv8',
      'Dual Mystic Lapis Lv6',
    ],
  },
  {
    id: 66,
    Helmet: [
      'Mystic Lapis Lv9',
      'Wise Lapis Lv9',
      'Dual Wise Lapis Lv6',
      'Triple Mystic',
      'Life Lapis Lv7',
      'Life Lapis Lv8',
    ],
    Armor: [
      'Elemental Lapis Lv2 || Elemental Orb',
      'Mystic Lapis Lv8',
      'Dual Wise Lapis Lv6',
      'Life Lapis Lv9',
      'Life Lapis Lv8',
      'Life Lapis Lv7',
    ],
    Gloves: [
      'Mystic Lapis Lv9',
      'Mystic Lapis Lv8',
      'Wise Lapis Lv9',
      'Wise Lapis Lv8',
      'Life Lapis Lv8',
      'Life Lapis Lv7',
    ],
    pants: [
      'Mystic Lapis Lv9',
      'Mystic Lapis Lv8',
      'Wise Lapis Lv9',
      'Wise Lapis Lv8',
      'Life Lapis Lv8',
      'Life Lapis Lv7',
    ],
    Boots: [
      'Mystic Lapis Lv8',
      'Wise Lapis Lv8',
      'Life Lapis Lv9',
      'Life Lapis Lv8',
      'Life Lapis Lv7',
      'Sonic Lapis Lv2',
    ],
  },
];

// export const X = [
//   {
//     id: 1,
//     title1: 'Normal Build',
//     link1: getLinkById(1),
//   },
//   {
//     id: 2,
//     title1: 'Battle Tank',
//     link1: getLinkById(2),
//     title2: 'True Tank',
//     link2: getLinkById(3),
//   },
// ];
