// id=,
// title1=,
// link1=,
// title2=,
// link2=,

export const LINKS = [
  //1
  {
    id: 1,
    helm: [
      'Craft Lapis Lv9',
      'Shrewd Lapis Lv9',
      'Dual Craft Lapis Lv6',
      'Dual Fortune Lapis Lv6',
      'Heart Lapis',
      'Star Lapis / Pure Lapis / Triple Craft',
    ],
    armor: [
      'Craft Lapis Lv8',
      'Craft Lapis Lv7',
      'Shrewd Lapis Lv8',
      'Shrewd Lapis Lv7',
      'Dual Craft Lapis Lv6',
      'Elemental Lapis Lv2 / Elemental Orb',
    ],
    gloves: [
      'Craft Lapis Lv9',
      'Shrewd Lapis Lv9',
      'Shrewd Lapis Lv8',
      'Shrewd Lapis Lv7',
      'Dual Craft Lapis Lv6',
      'Dual Fortune Lapis Lv6 / Triple Craft',
    ],
    legs: [
      'Craft Lapis Lv9',
      'Craft Lapis Lv8',
      'Craft Lapis Lv7',
      'Shrewd Lapis Lv9',
      'Dual Craft Lapis Lv6',
      'Dual Fortune Lapis Lv6 / Triple Craft',
    ],
    boots: [
      'Craft Lapis Lv8',
      'Craft Lapis Lv7',
      'Shrewd Lapis Lv8',
      'Shrewd Lapis Lv7',
      'Dual Craft Lapis Lv6',
      'Sonic Lapis Lv2',
    ],
  },
  //2
  {
    id: 2,
    helm: [
      'Craft Lapis Lv9',
      'Shrewd Lapis Lv9',
      'Dual Craft Lapis Lv6',
      'Dual Fortune Lapis Lv6',
      'Heart Lapis',
      'Star Lapis / Pure Lapis / Triple Craft Lapis',
    ],
    armor: [
      'Craft Lapis Lv8',
      'Craft Lapis Lv7',
      'Shrewd Lapis Lv8',
      'Shrewd Lapis Lv7',
      'Dual Craft Lapis Lv6',
      'Elemental Lapis Lv2 / Elemental Orb',
    ],
    gloves: [
      'Craft Lapis Lv9',
      'Shrewd Lapis Lv9',
      'Shrewd Lapis Lv8',
      'Shrewd Lapis Lv7',
      'Dual Craft Lapis Lv6',
      'Dual Fortune Lapis Lv6 / Triple Craft Lapis',
    ],
    legs: [
      'Craft Lapis Lv9',
      'Craft Lapis Lv8',
      'Craft Lapis Lv7',
      'Shrewd Lapis Lv9',
      'Dual Craft Lapis Lv6',
      'Dual Fortune Lapis Lv6 / Triple Craft Lapis',
    ],
    boots: [
      'Craft Lapis Lv8',
      'Craft Lapis Lv7',
      'Shrewd Lapis Lv8',
      'Shrewd Lapis Lv7',
      'Dual Craft Lapis Lv6',
      'Sonic Lapis Lv2',
    ],
    shield: [
      'Craft Lapis Lv9',
      'Craft Lapis Lv8',
      'Craft Lapis Lv7',
      'Shrewd Lapis Lv9',
      'Dual Craft Lapis Lv6',
      'Dual Fortune Lapis Lv6 / Triple Craft Lapis',
    ],
  },
  //3
  {
    id: 3,
    helm: [
      'Life Lapis Lv8',
      'Life Lapis Lv7',
      'Safe Lapis Lv9',
      'Wit Lapis Lv7',
      'Wit Lapis Lv6',
      'Triple Craft Lapis',
    ],
    armor: [
      'Absorption Lapis Lv9',
      'Absorption Lapis Lv8',
      'Absorption Lapis Lv7',
      'Life Lapis Lv9',
      'Life Lapis Lv8',
      '1 top = Life Lapis Lv7 || 2+ tops = Elemental Lapis Lv2 / Elemental Orb',
    ],
    gloves: [
      'Absorption Lapis Lv9',
      'Absorption Lapis Lv8',
      'Absorption Lapis Lv7',
      'Absorption Lapis Lv6 / Safe Lapis Lv9',
      'Life Lapis Lv8',
      'Life Lapis Lv7',
    ],
    legs: [
      'Absorption Lapis Lv9',
      'Absorption Lapis Lv8',
      'Absorption Lapis Lv7',
      'Absorption Lapis Lv6 / Safe Lapis Lv9',
      'Life Lapis Lv8',
      'Life Lapis Lv7',
    ],
    boots: [
      'Absorption Lapis Lv9',
      'Absorption Lapis Lv8',
      'Absorption Lapis Lv7',
      'Life Lapis Lv9',
      'Life Lapis Lv8',
      'Sonic Lapis Lv2',
    ],
    shield: [
      'Absorption Lapis Lv9',
      'Absorption Lapis Lv8',
      'Absorption Lapis Lv7',
      'Absorption Lapis Lv6 / Safe Lapis Lv9',
      'Life Lapis Lv8',
      'Life Lapis Lv7',
    ],
  },
];

// export const X = [
//   {
//     id: 1,
//     title1: 'Normal Build',
//     link1: getLinkById(1),
//   },
//   {
//     id: 2,
//     title1: 'Battle Tank',
//     link1: getLinkById(2),
//     title2: 'True Tank',
//     link2: getLinkById(3),
//   },
// ];
